import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/styles/css/globals.css';
import '@/styles/scss/config.scss';
import { AuthProvider } from '@/auth/AuthProvide';
import { AppDataProvider } from '@/context/AppData';
const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'],
});
export const metadata: Metadata = {
    title: 'Chat App',
    description: 'Chat app generated by create next app',
    icons: ['./logo.png'],
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <AuthProvider>
                    <AppDataProvider>{children}</AppDataProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
